/data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.csh: line 1: setenv: command not found
/data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.csh: line 2: setenv: command not found
/data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.csh: line 3: setenv: command not found
/data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.csh: line 4: setenv: command not found
/data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.csh: line 34: syntax error near unexpected token `"${1}"'
/data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.csh: line 34: `    switch ( "${1}" )'
Traceback (most recent call last):
  File "/home/cs601-pwang71/pwang71/ml_prj/main.py", line 99, in <module>
    edudataset = load_dataset("json", data_files="./data/train.json")
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/load.py", line 2259, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/load.py", line 1799, in dataset_module_factory
    ).get_module()
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/load.py", line 1141, in get_module
    data_files = DataFilesDict.from_patterns(
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/data_files.py", line 715, in from_patterns
    DataFilesList.from_patterns(
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/data_files.py", line 620, in from_patterns
    resolve_pattern(
  File "/home/cs601-pwang71/.conda/envs/ml_final/lib/python3.10/site-packages/datasets/data_files.py", line 407, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/home/cs601-pwang71/pwang71/ml_prj/./data/train.json'
